apiVersion: v1
kind: Service
metadata:
  name: frontend-connect
  labels:
    # Enables "zarf connect frontend-connect"
    zarf.dev/connect-name: frontend-connect
  annotations:
    zarf.dev/connect-description: "The application frontend"
spec:
  selector:
    app.kubernetes.io/instance: frontend
    app.kubernetes.io/name: frontend
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80